import Features from "@/components/Features";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import HowWorks from "@/components/HowWorks";
import Pricing from "@/components/Pricing";
import Testimonial from "@/components/Testimonial";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>API Provider</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   <Header />
   <HeroSection/>
   <HowWorks/>
   <Features/>
   <Pricing/>

   <Footer/>
    </>
  );
}
